# Generated by Django 5.2.6 on 2025-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_collaborationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
